### ISSUE TITLE
how to use in centos

### ISSUE THREAD

**Issue by James-Yan** [silenceper/gowatch#1]
silenceper你好，我按照你的说明安装了gowatch，发现根本没法直接使用gowatch命令，麻烦具体说明下，我用的是centos7系统

**Comment by silenceper** [comment]
请问有报错信息吗？
在使用安装`go get github.com/silenceper/gowatch`之后返回是什么？

**Comment by James-Yan** [comment]
好了，将$GOPATH:/bin加入环境变量就好了，第一次弄这个
