### ISSUE TITLE
配置文件不支持自定义命令

### ISSUE THREAD

**Issue by slevinsc** [silenceper/gowatch#22]
如题

**Comment by silenceper** [comment]
编译成功之后的，运行命令么？

**Comment by slevinsc** [comment]
不是编译成功，是监控到文件变化，调用我定义的命令编译，比如我是用Make来编译的

**Comment by silenceper** [comment]
不支持自定义编译，因为通过Makefile编译，目标文件的生成不是由gowatch控制。
你可以将Makefile 内build参数提取出来。
