### ISSUE TITLE
建议：新增初始化gowatch.yml文件

### ISSUE THREAD

**Issue by Baiyuetribe** [silenceper/gowatch#33]
我使用vue3+go-fiber开发，之前使用air热更新，但是air存在屏蔽日志输出和卡死进程的问题，换了gowatch后一切正常。唯一不足的是需要手动创建一个gowatch.yml文件，希望增加gowatch init命令，用于初始化一个gowatch.yml文件。

**Comment by silenceper** [comment]
good idea 👍

**Comment by yanue** [comment]
已提交pr
