### ISSUE TITLE
How to disable DEBUG and INFO

### ISSUE THREAD

**Issue by memark** [silenceper/gowatch#41]
This tool works nicely!

But there is a lot of noise in the output:

```
2021/11/29 08:45:26 gowatch.go:113: [INFO] Start building...
2021/11/29 08:45:26 gowatch.go:150: [INFO] Build Args: go build -o ./00
2021/11/29 08:45:26 gowatch.go:158: [INFO] Build was successful
2021/11/29 08:45:26 gowatch.go:193: [DEBUG] main pid: 6059
2021/11/29 08:45:26 gowatch.go:194: [DEBUG] pids: []
2021/11/29 08:45:26 gowatch.go:205: [DEBUG] killing MAIN process pid: 6059
```

```
❯ gowatch -v
1.5
```

Is there a config setting to disable the printing of DEBUG and INFO lines?
I find they take too much focus from the output from my actual program. (ERROR lines are still useful.)

**Comment by silenceper** [comment]
Thanks for the feedback.

Currently does not support custom log output level, but I will add the change function later.

**Comment by silenceper** [comment]
@memark  
two way can custom log level:
-  add `-l` flag, like `gowatch -l error`
-  set `log_level` field in the gowatch.yml
```
Usage of gowatch:

If no command is provided gowatch will start the runner with the provided flags

Commands:
  init  creates a gowatch.yml file with default settings to the current directory

Flags:
  -args string
    	app run args,separated by commas. like: -args='-host=:8080,-name=demo'
  -h	help
  -l string
    	log level: debug, info, warn, error, fatal
  -o string
    	go build output
  -p string
    	go build packages
  -v	show version
```

**Comment by silenceper** [comment]
please use this version: https://github.com/silenceper/gowatch/releases/tag/v1.5.2-rc.2

**Comment by memark** [comment]
@silenceper Excellent, thanks!!
