### ISSUE TITLE
repository 'https://github.com/nestgo/log/' not found

### ISSUE THREAD

**Issue by pengliheng** [silenceper/gowatch#6]
> Windows PowerShell
> 版权所有 (C) 2016 Microsoft Corporation。保留所有权利。
> 
> PS D:\WWW\blog> go get github.com/silenceper/gowatch
> \# cd .; git clone https://github.com/nestgo/log C:\Users\33318\go\src\github.com\nestgo\log
> Cloning into 'C:\Users\33318\go\src\github.com\nestgo\log'...
> remote: Repository not found.
> fatal: repository 'https://github.com/nestgo/log/' not found
> package github.com/nestgo/log: exit status 128
> PS D:\WWW\blog>

**Comment by pengliheng** [comment]
nestgo/log   是啥？？？

**Comment by silenceper** [comment]
你再重试下，因为导入了一个不存在的包 😢
